---
title: "Welcome to R-Vogg-Blog"
author:
  - name: Richard Vogg
    url: https://github.com/richardvogg
    affiliation: independent
    affiliation_url: https://github.com/richardvogg
date: 10-09-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE,message=FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


I am using R almost every day for the analysis of data.

After reading [this](https://medium.com/@racheltho/why-you-yes-you-should-blog-7d2544ac1045) great blogpost by Rachel Thomas, called "Why you (yes, you) should blog" I started playing around with the idea of writing down some of the things I learn.

Especially this point resonated a lot in me:

> You are best positioned to help people one step behind you. The material is still fresh in your mind. Many experts have forgotten what it was like to be a beginner (or an intermediate) and have forgotten why the topic is hard to understand when you first hear it. The context of your particular background, your particular style, and your knowledge level will give a different twist to what you’re writing about.
> `r tufte::quote_footer('--- Rachel Thomas')`

The next event that brought me closer to this blog was a tutorial by Maëlle Salmon during Latin-R 2020. The material can be found [here](https://bloguearrr.netlify.app/intro/starters/). She showed how easy it is to get started with {distill} and how to setup a blog.

The last ingredient I needed were topics to write about. As I will be speaking about Data Composition during rstudio::global(2021), I thought this was a great opportunity to summarize some methods and ideas around this topic.